import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { useState } from "react";
import { Sparkles, Mic, Scissors, Type, Gauge, Play, Wand2, Loader2 } from "lucide-react";
import { AppShell } from "../components/app-shell";
import { HoloCard } from "../components/holo-card";
import { ScoreBar } from "../components/score-bar";

export const Route = createFileRoute("/clone")({
  head: () => ({ meta: [{ title: "Clone Studio — ViralReel AI" }] }),
  component: ClonePage,
});

const fingerprint = [
  { label: "Editing style", value: 92, icon: Scissors },
  { label: "Voice signature", value: 88, icon: Mic },
  { label: "Hook patterns", value: 84, icon: Sparkles },
  { label: "Subtitle rhythm", value: 79, icon: Type },
  { label: "Pacing behavior", value: 91, icon: Gauge },
];

const cloned = [
  { title: "Cyberpunk POV: rainy Tokyo", score: 89, color: "from-cyan-400/40 to-fuchsia-500/40" },
  { title: "3 things I wish I knew at 22", score: 84, color: "from-fuchsia-500/40 to-rose-500/40" },
  { title: "Studio reset · ambient cut", score: 78, color: "from-violet-500/40 to-cyan-400/40" },
  { title: "Drone reveal: alpine roads", score: 92, color: "from-emerald-400/40 to-cyan-400/40" },
];

function ClonePage() {
  const [training, setTraining] = useState(false);
  return (
    <AppShell title="Clone Studio">
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <HoloCard className="xl:col-span-2 p-6 relative overflow-hidden">
          <div className="absolute -top-20 -right-10 size-72 rounded-full bg-fuchsia-500/20 blur-3xl"/>
          <div className="relative">
            <div className="text-xs uppercase tracking-[0.2em] text-cyan-300">AI Creator Clone</div>
            <h2 className="mt-1 text-3xl font-semibold">Generate reels in <span className="text-holo">your exact style</span>.</h2>
            <p className="text-sm text-muted-foreground mt-2 max-w-xl">We learned your edits, voice, hooks and pacing from 142 of your reels. Spin up endless variations that still sound like you.</p>

            <div className="mt-6 grid sm:grid-cols-2 gap-4">
              {fingerprint.map((f) => (
                <div key={f.label} className="glass rounded-xl p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <f.icon className="size-4 text-cyan-300"/>
                    <span className="text-sm font-medium">{f.label}</span>
                    <span className="ml-auto text-xs text-muted-foreground tabular-nums">{f.value}%</span>
                  </div>
                  <ScoreBar label="match" value={f.value} accent="holo"/>
                </div>
              ))}
            </div>

            <div className="mt-6 flex flex-wrap gap-3 items-center">
              <button
                onClick={() => { setTraining(true); setTimeout(() => setTraining(false), 2200); }}
                className="inline-flex items-center gap-2 rounded-xl px-5 py-3 bg-gradient-to-r from-cyan-400 to-fuchsia-500 text-black font-medium glow-magenta hover:opacity-90"
              >
                {training ? <Loader2 className="size-4 animate-spin"/> : <Wand2 className="size-4"/>}
                {training ? "Cloning…" : "Generate in my style"}
              </button>
              <button className="inline-flex items-center gap-2 glass rounded-xl px-4 py-2.5 text-sm hover:bg-white/10">
                Retrain from latest 30 reels
              </button>
            </div>
          </div>
        </HoloCard>

        {/* Training orb */}
        <div className="glass rounded-2xl p-6 flex flex-col items-center justify-center text-center">
          <div className="relative size-40">
            <motion.div
              className="absolute inset-0 rounded-full bg-gradient-to-br from-cyan-400 via-fuchsia-500 to-violet-500 blur-2xl opacity-60"
              animate={{ scale: [1, 1.15, 1] }}
              transition={{ duration: 3, repeat: Infinity }}
            />
            <motion.div
              className="absolute inset-4 rounded-full bg-gradient-to-br from-cyan-400 via-fuchsia-500 to-violet-500 ring-2 ring-white/20"
              animate={{ rotate: 360 }}
              transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
            />
            <div className="absolute inset-0 grid place-items-center text-3xl font-semibold">87%</div>
          </div>
          <div className="mt-4 text-sm font-medium">Clone fidelity</div>
          <div className="text-xs text-muted-foreground mt-1">Updated 8m ago · 142 reels learned</div>
        </div>
      </div>

      {/* Cloned reels grid */}
      <div className="mt-6 glass rounded-2xl p-6">
        <div className="flex items-center justify-between">
          <div>
            <div className="text-xs uppercase tracking-wider text-muted-foreground">Generated by your clone</div>
            <h2 className="text-lg font-semibold mt-1">Fresh drafts in your voice</h2>
          </div>
          <button className="text-xs glass rounded-lg px-3 py-1.5 hover:bg-white/10">Regenerate all</button>
        </div>
        <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">
          {cloned.map((r) => (
            <motion.div key={r.title} whileHover={{ y: -4 }} className="glass rounded-xl overflow-hidden">
              <div className={`aspect-[9/12] bg-gradient-to-br ${r.color} relative`}>
                <Play className="absolute inset-0 m-auto size-10 opacity-90"/>
                <div className="absolute top-2 left-2 glass rounded-full px-2 py-0.5 text-[10px] flex items-center gap-1">
                  <Sparkles className="size-3 text-cyan-300"/>Cloned
                </div>
                <div className="absolute bottom-2 right-2 glass rounded-full px-2 py-0.5 text-[10px]">Viral {r.score}</div>
              </div>
              <div className="p-3 text-sm font-medium truncate">{r.title}</div>
            </motion.div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
